### PR TITLE
Division panel overhaul

### PR DESCRIPTION
**Pull request by jessecoleman**
- fix most checkbox selection behavior, fix sorting so name is asc and numerical columns are descending by default
- fix filtering by agency/org on all endpoints
- add expand/collapse all button to division table
- change indexer to populate cat2
- display correctly aggregated directorate totals

### CODE REVIEW

**Review by h1-the-swan — CHANGES_REQUESTED** [review]
Getting this error from the frontend on compile:

```
frontend_1       | Failed to compile.
frontend_1       |
frontend_1       | ./src/app/actions.ts
frontend_1       | Attempted import error: 'DefaultService' is not exported from 'api' (imported as 'Service').
```

**Comment by jessecoleman** [comment]
> Getting this error from the frontend on compile:
> 
> ```
> frontend_1       | Failed to compile.
> frontend_1       |
> frontend_1       | ./src/app/actions.ts
> frontend_1       | Attempted import error: 'DefaultService' is not exported from 'api' (imported as 'Service').
> ```

I think you may need to update the `codegen` dependency.

**Comment by h1-the-swan** [comment]
Can you check that the version is correct in this branch's `package.json`?

**Comment by jessecoleman** [comment]
> Can you check that the version is correct in this branch's `package.json`?

Try now

**Review by h1-the-swan — APPROVED** [review]
Looks good!

**Pull request merged**
